name: Lint # name of the action (displayed in the github interface)

on: # event list
  pull_request: # on a pull request to each of these branches
    branches:
      - develop
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Install flake8
        run: pip install flake8==4.0.1
      - name: Install markupsafe
        run: pip install MarkupSafe==2.0.1
      - name: Install Jinja2
        run: pip install Jinja2==2.11.3
      - name: Run flake8
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          failIf: any
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "--ignore=E121,E123 ."