name: Lint # name of the action (displayed in the github interface)

on: # event list
  pull_request: # on a pull request to each of these branches
    branches:
      - develop
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Run flake8
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          failIf: any
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "--ignore=E121,E123 ."